### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by xk-huang** [eth-ait/phys-fullbody-grasp#1]
Hi, @braunjon !

Thank you for the excellent work! I was wondering if there is a specific date for the code release. I believe this codebase will be immensely beneficial for newcomers to the field!

**Comment by braunjon** [comment]
Hi @xk-huang 
Sorry, atm I do not have a release date. But the code builds on https://github.com/nv-tlabs/ASE.

**Comment by xk-huang** [comment]
Thanks for the reference!
